name: Deploy Solution_One

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/Solution_One_Server

            echo "📥 Pull latest code"
            git fetch origin
            git reset --hard origin/main

            echo "🐳 Stop old container"
            docker compose down || true

            echo "🚀 Start new container"
            docker compose up -d --build

            echo "📋 Logs"
            docker compose logs --tail=20